export type {
  ResumeDocument,
  SchemaVersion,
  DocumentMeta,
  Basics,
  Profile,
  Section,
  WorkSection,
  EducationSection,
  ProjectsSection,
  SkillsSection,
  CertificatesSection,
  LanguagesAndInterestsSection,
  AwardsSection,
  WorkItem,
  EducationItem,
  ProjectItem,
  SkillItem,
  CertificateItem,
  AwardItem,
  LanguageItem,
  InterestItem,
  LayoutConfig,
  ThemeOverrides,
} from './resume-schema'
