/** Frozen Figma Make template typography and spacing baselines. */
export const TypographyBaseline = {
  font: {
    name: 22,
    headline: 10.5,
    contact: 9,
    summary: 9.5,
    sectionHead: 8,
    entryTitle: 11,
    entryDate: 9,
    entrySub: 10,
    body: 9.5,
    skillName: 9.5,
    skillLevel: 8,
    skillKeywords: 9,
    certName: 9.5,
    certMeta: 8.5,
    keyword: 8.5,
    langLabel: 8.5,
    langValue: 9.5,
  },
  lineHeight: {
    name: 1.1,
    headline: 1.3,
    contact: 1.7,
    summary: 1.6,
    sectionHead: 1,
    entry: 1.3,
    body: 1.45,
    keyword: 1.4,
    skillKeywords: 1.45,
  },
  spacing: {
    sectionGap: 9,
    headlineMarginTop: 3,
    contactPaddingTop: 2,
    summaryMarginTop: 9,
    secHeadMarginBottom: 5,
    secHeadRuleMarginTop: 3,
    entryHeadMarginBottom: 2,
    entrySubMarginTop: 1,
    keywordPaddingTop: 3,
    bulletMarginBottom: 1,
    bulletGap: 5,
    skillRowGap: 3,
    certRowGap: 2.5,
    langRowGap: 3,
    continuationPaddingTop: 5,
  },
} as const
