#!/usr/bin/env node
// install-skills.mjs — wire the skills/ package into any supported coding agent.
//
// Usage:
//   node scripts/install-skills.mjs <agent>            # install for one agent
//   node scripts/install-skills.mjs all                # install for every supported agent
//   node scripts/install-skills.mjs <agent> --user     # personal scope (Claude only)
//   node scripts/install-skills.mjs <agent> --dry-run  # show the plan, write nothing
//   node scripts/install-skills.mjs <agent> --copy     # copy instead of symlink (Claude)
//   node scripts/install-skills.mjs --uninstall <agent>|all
//
// Zero dependencies. Requires Node 18+.

import {
  mkdirSync,
  readdirSync,
  writeFileSync,
  existsSync,
  statSync,
  symlinkSync,
  rmSync,
  cpSync,
  lstatSync,
} from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { homedir, platform } from 'node:os'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(HERE, '..')
const SKILLS_DIR = join(REPO_ROOT, 'skills')
const AGENTS_MD = join(REPO_ROOT, 'AGENTS.md')

const SKILL_NAMES = readdirSync(SKILLS_DIR)
  .filter(
    (n) => !n.startsWith('.') && statSync(join(SKILLS_DIR, n)).isDirectory(),
  )
  .filter((n) => existsSync(join(SKILLS_DIR, n, 'SKILL.md')))

const BANNER_LINES = [
  '<!--',
  '  Generated by `pnpm skills:install`. DO NOT EDIT THIS FILE.',
  '  Edit the canonical source under skills/<name>/SKILL.md and re-run the installer.',
  '-->',
  '',
]

// Compute the markdown-friendly relative path from `fromFile` (the adapter we are
// writing) to `toPath` (a target inside the repo). Always uses '/' separators
// and prepends './' for siblings/descendants so the link is unambiguous.
function relLink(fromFile, toPath) {
  const rel = relative(dirname(fromFile), toPath).split(/[\\/]/).join('/')
  if (rel === '') return '.'
  if (rel.startsWith('.')) return rel
  return `./${rel}`
}

function pointerMarkdown({
  targetFile,
  heading = 'Resume-as-Code Agent Rules',
  extraNote = '',
}) {
  const agentsLink = relLink(targetFile, AGENTS_MD)
  const skillsLink = relLink(targetFile, SKILLS_DIR)
  const lines = [
    ...BANNER_LINES,
    `# ${heading}`,
    '',
    `This project uses the [AGENTS.md](${agentsLink}) standard as the canonical agent workflow definition.`,
    '',
    `Three Agent Skills live under [\`skills/\`](${skillsLink}):`,
    '',
    ...SKILL_NAMES.map(
      (n) =>
        `- [\`${n}\`](${relLink(targetFile, join(SKILLS_DIR, n, 'SKILL.md'))})`,
    ),
    '',
    'Before acting on any request related to resumes, timelines, or interview prep,',
    `read [AGENTS.md](${agentsLink}) and then the relevant \`SKILL.md\`.`,
  ]
  if (extraNote) {
    lines.push('', extraNote)
  }
  return lines.join('\n') + '\n'
}

// Adapter table.
// Each entry describes one agent: the install function returns the list of
// files it would write (for dry-run/uninstall), and `uninstall` lists the same
// paths so they can be cleanly removed.
const AGENTS = {
  // --- Native AGENTS.md readers: AGENTS.md is committed at the repo root, so
  // installing is a no-op for these agents. We still expose them so users get
  // a clear "you're done" message. ---
  codex: {
    label: 'Codex CLI / Codex Web',
    native: true,
    install: () => [{ path: AGENTS_MD, action: 'exists (committed)' }],
  },
  opencode: {
    label: 'OpenCode',
    native: true,
    install: () => [{ path: AGENTS_MD, action: 'exists (committed)' }],
  },
  aider: {
    label: 'Aider',
    native: true,
    install: () => [{ path: AGENTS_MD, action: 'exists (committed)' }],
  },
  qoder: {
    label: 'Qoder',
    native: true,
    install: () => [{ path: AGENTS_MD, action: 'exists (committed)' }],
  },
  continue: {
    label: 'Continue',
    native: true,
    install: () => [{ path: AGENTS_MD, action: 'exists (committed)' }],
  },

  // --- Claude Code: per-skill folders under .claude/skills/ ---
  claude: {
    label: 'Claude Code',
    install: ({ userScope, copyMode, dryRun }) => {
      const root = userScope
        ? join(homedir(), '.claude')
        : join(REPO_ROOT, '.claude')
      const targetDir = join(root, 'skills')
      const files = []
      if (!dryRun) mkdirSync(targetDir, { recursive: true })
      for (const name of SKILL_NAMES) {
        const src = join(SKILLS_DIR, name)
        const dst = join(targetDir, name)
        if (!dryRun) {
          if (existsSync(dst) || isSymlink(dst))
            rmSync(dst, { recursive: true, force: true })
          if (copyMode || platform() === 'win32') {
            cpSync(src, dst, { recursive: true })
          } else {
            symlinkSync(relative(targetDir, src), dst, 'dir')
          }
        }
        files.push({
          path: dst,
          action: copyMode || platform() === 'win32' ? 'copy' : 'symlink',
        })
      }
      return files
    },
    uninstall: ({ userScope }) => {
      const root = userScope
        ? join(homedir(), '.claude')
        : join(REPO_ROOT, '.claude')
      const targetDir = join(root, 'skills')
      return SKILL_NAMES.map((n) => join(targetDir, n))
    },
  },

  // --- GitHub Copilot: single instructions file ---
  copilot: {
    label: 'GitHub Copilot',
    install: ({ dryRun }) => {
      const target = join(REPO_ROOT, '.github', 'copilot-instructions.md')
      if (!dryRun) {
        mkdirSync(dirname(target), { recursive: true })
        writeFileSync(
          target,
          pointerMarkdown({
            targetFile: target,
            heading: 'GitHub Copilot Project Rules',
          }),
        )
      }
      return [{ path: target, action: 'write' }]
    },
    uninstall: () => [join(REPO_ROOT, '.github', 'copilot-instructions.md')],
  },

  // --- Cursor: .mdc rule with frontmatter ---
  cursor: {
    label: 'Cursor',
    install: ({ dryRun }) => {
      const target = join(REPO_ROOT, '.cursor', 'rules', 'resume-as-code.mdc')
      const body = [
        '---',
        'description: Resume-as-Code workflow rules. Read AGENTS.md and the relevant skills/<name>/SKILL.md before acting on resume, timeline, or interview tasks.',
        'alwaysApply: true',
        '---',
        '',
        pointerMarkdown({
          targetFile: target,
          heading: 'Cursor Project Rules',
        }),
      ].join('\n')
      if (!dryRun) {
        mkdirSync(dirname(target), { recursive: true })
        writeFileSync(target, body)
      }
      return [{ path: target, action: 'write' }]
    },
    uninstall: () => [
      join(REPO_ROOT, '.cursor', 'rules', 'resume-as-code.mdc'),
    ],
  },

  // --- Trae: project_rules.md under .trae/rules/ ---
  trae: {
    label: 'Trae',
    install: ({ dryRun }) => {
      const target = join(REPO_ROOT, '.trae', 'rules', 'project_rules.md')
      if (!dryRun) {
        mkdirSync(dirname(target), { recursive: true })
        writeFileSync(
          target,
          pointerMarkdown({
            targetFile: target,
            heading: 'Trae Project Rules',
          }),
        )
      }
      return [{ path: target, action: 'write' }]
    },
    uninstall: () => [join(REPO_ROOT, '.trae', 'rules', 'project_rules.md')],
  },

  // --- Windsurf: .windsurf/rules/<name>.md (current Windsurf format) ---
  windsurf: {
    label: 'Windsurf',
    install: ({ dryRun }) => {
      const target = join(REPO_ROOT, '.windsurf', 'rules', 'resume-as-code.md')
      if (!dryRun) {
        mkdirSync(dirname(target), { recursive: true })
        writeFileSync(
          target,
          pointerMarkdown({
            targetFile: target,
            heading: 'Windsurf Project Rules',
          }),
        )
      }
      return [{ path: target, action: 'write' }]
    },
    uninstall: () => [
      join(REPO_ROOT, '.windsurf', 'rules', 'resume-as-code.md'),
    ],
  },

  // --- Cline / RooCode: .clinerules file (also picked up by RooCode) ---
  cline: {
    label: 'Cline / RooCode',
    install: ({ dryRun }) => {
      const target = join(REPO_ROOT, '.clinerules')
      if (!dryRun)
        writeFileSync(
          target,
          pointerMarkdown({
            targetFile: target,
            heading: 'Cline / RooCode Project Rules',
          }),
        )
      return [{ path: target, action: 'write' }]
    },
    uninstall: () => [join(REPO_ROOT, '.clinerules')],
  },
}

function isSymlink(p) {
  try {
    return lstatSync(p).isSymbolicLink()
  } catch {
    return false
  }
}

function parseArgs(argv) {
  const opts = {
    agent: null,
    dryRun: false,
    userScope: false,
    copyMode: false,
    uninstall: false,
  }
  for (const arg of argv) {
    if (arg === '--dry-run') opts.dryRun = true
    else if (arg === '--user') opts.userScope = true
    else if (arg === '--copy') opts.copyMode = true
    else if (arg === '--uninstall') opts.uninstall = true
    else if (!arg.startsWith('--')) opts.agent ??= arg
  }
  return opts
}

function printHelp() {
  console.log(`
Usage:
  pnpm skills:install <agent>            install for one agent
  pnpm skills:install all                install for every supported agent
  pnpm skills:install <agent> --user     personal scope (Claude only — installs into ~/.claude/skills/)
  pnpm skills:install <agent> --dry-run  show the plan, write nothing
  pnpm skills:install <agent> --copy     copy instead of symlink (Claude)
  pnpm skills:uninstall <agent>|all

Supported agents:`)
  for (const [key, def] of Object.entries(AGENTS)) {
    console.log(
      `  ${key.padEnd(10)} ${def.label}${def.native ? ' (zero-config — uses AGENTS.md)' : ''}`,
    )
  }
  console.log('')
}

function runInstall(agentKey, opts) {
  const def = AGENTS[agentKey]
  if (!def) {
    console.error(`Unknown agent: ${agentKey}`)
    printHelp()
    process.exitCode = 1
    return
  }
  if (def.native && !opts.dryRun) {
    console.log(
      `✓ ${def.label}: zero-config. Reads AGENTS.md at the repo root. Nothing to install.`,
    )
    return
  }
  const files = def.install(opts)
  const verb = opts.dryRun ? 'Would write' : 'Wrote'
  for (const f of files) {
    console.log(
      `  ${verb}: ${relative(REPO_ROOT, f.path) || f.path}  [${f.action}]`,
    )
  }
  if (!opts.dryRun) console.log(`✓ ${def.label}: installed.`)
}

function runUninstall(agentKey) {
  const def = AGENTS[agentKey]
  if (!def) {
    console.error(`Unknown agent: ${agentKey}`)
    process.exitCode = 1
    return
  }
  if (def.native) {
    console.log(`✓ ${def.label}: nothing to uninstall (zero-config).`)
    return
  }
  const paths = def.uninstall({ userScope: false })
  for (const p of paths) {
    if (existsSync(p) || isSymlink(p)) {
      rmSync(p, { recursive: true, force: true })
      console.log(`  Removed: ${relative(REPO_ROOT, p) || p}`)
    }
  }
  console.log(`✓ ${def.label}: uninstalled.`)
}

function main() {
  const opts = parseArgs(process.argv.slice(2))
  if (
    !opts.agent ||
    opts.agent === 'help' ||
    opts.agent === '--help' ||
    opts.agent === '-h'
  ) {
    printHelp()
    return
  }
  const targets = opts.agent === 'all' ? Object.keys(AGENTS) : [opts.agent]
  for (const a of targets) {
    if (opts.uninstall) runUninstall(a)
    else runInstall(a, opts)
  }
}

main()
